### ISSUE TITLE
Wireguard on USB Armory with Tamago unikernel?

### ISSUE THREAD

**Issue by t-anon** [f-secure-foundry/usbarmory#66]
Is it possible to run wireguard-go on the USB Armory on the Tamago unikernel? Or, would it be possible, with some minor changes to the Wireguard project? I think this might be promising for usage as a particularly secure VPN.

**Comment by abarisani** [comment]
Because of [this](https://twitter.com/hugelgupf/status/1349837585342894081?s=20) I think it might be possible.

It would basically be an effort to bridge our [network driver](https://github.com/f-secure-foundry/imx-usbnet) (which uses gVisor) with it.

We have no current plans of doing this but I think it could be feasible.

Please note that [imx-usbnet](https://github.com/f-secure-foundry/imx-usbnet) is currently only supported on Linux hosts, so that is a limitation.

Cheers
