### ISSUE TITLE
feature request: secure boot and root encryption

### ISSUE THREAD

**Issue by Yalman** [f-secure-foundry/usbarmory#70]
Hi,

could you please write me a manual describing Secure Boot and root encryption?
I'm a beginner and i don't want to make mistakes.

best regards

**Comment by Yalman** [comment]
![IMG_20211207_202202](https://user-images.githubusercontent.com/6912504/145093226-da7201d0-12cc-43d1-9bb7-34cf7be2aa64.jpg)

I miss usable GPIOs on the MK2
Idea for the next generation usbarmory. A oled display for one-time-password or other stuff. And maybe a button to response something.

**Comment by abarisani** [comment]
Please check our [wiki](https://github.com/f-secure-foundry/usbarmory/wiki/Secure-boot-(Mk-II))

GPIOs can be access through the [debug accessory](https://github.com/f-secure-foundry/usbarmory/tree/master/hardware/mark-two-debug-accessory).

I'd suggest raising these questions on our [support group](https://groups.google.com/d/forum/usbarmory) or [email](https://github.com/f-secure-foundry/usbarmory/wiki#support) rather than opening github issues.

Thanks!
